### ISSUE TITLE
Issue with multiple Keyboard layout configured...

### ISSUE THREAD

**Issue by BUGgs** [ierton/xkb-switch#5] opened 2013-07-17 15:57 UTC
Hi,
I have an issue when I'm configuring multiple keyboard at the same time. (with only 1 keyboard, it's always ok)

Actually, I'm using xkb-switch just to know which keyboard is the ACTIVE one, but in some case it return the wrong keyboard:
Configured : German, French, US-Intl
Default one: French

xkb-switch is always giving to me the active one, even when I switch with shortcut CTRL-SHIFT... Perfect...

BUT:
Configured : German, French, US-Intl
Default one: German

kxb-switch is not correct... He is mixing French and US-Intl:
Active keyboard: German --> xkb-result : de
Active keyboard: French --> xkb-result : US-Intl
Active keyboard: US-Intl --> xkb-result : fr(winkeys)

Os: Ubuntu 10.04 / XFCE / ARM CPU

**Comment by ierton** [comment] 2016-02-26 14:28
Hi, @BUGgs ! Could you please re-test the application? We have redesigned the X11-driver code, it may fix your issue.

**Comment by grwlf** [comment] 2017-03-13 08:28
I am closing this one due to timeout.. Please, reopen if the problem is still here.

**Closed by grwlf** 2017-03-13 08:28 UTC
